import { useMemo, useState } from 'react'
import type { ExecutionEvent } from '../../api/keyTaskWorkspace'
import { formatDateTime, sourceLabel } from './workspaceFormat'

const filters = [{ key: 'all', label: '全部' }, { key: 'work_submission', label: '工作提交' }, { key: 'meeting_progress_review', label: '会议纪要' }, { key: 'achievement', label: '成果' }, { key: 'issue', label: '问题' }, { key: 'execution_plan', label: '计划变更' }]

export function ExecutionTimeline({ events }: { events: ExecutionEvent[] }) {
  const [filter, setFilter] = useState('all')
  const visible = useMemo(() => filter === 'all' ? events : events.filter((event) => event.source_type === filter || event.event_type.startsWith(filter)), [events, filter])
  return <section className="rounded-lg border border-slate-300 border-l-4 border-l-blue-700 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold text-slate-900">⟳　推进记录</h2><div className="flex flex-wrap gap-2" aria-label="推进记录筛选">{filters.map((item) => <button key={item.key} type="button" onClick={() => setFilter(item.key)} className={`rounded-full px-3 py-1.5 text-sm ${filter === item.key ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>{item.label}</button>)}</div></div>{visible.length === 0 ? <div className="mt-5 flex min-h-20 items-center border-l-2 border-slate-200 pl-4 text-sm text-slate-500">暂无已确认的推进记录。</div> : <ol className="mt-5 space-y-0 border-l border-blue-200 pl-5">{visible.map((event) => <li key={event.id} className="relative pb-6 last:pb-0"><span className="absolute -left-[26px] top-1 grid size-4 place-items-center rounded-full border-2 border-blue-500 bg-white" /><div className="rounded-lg border border-slate-100 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold text-slate-800">{sourceLabel(event)} <span className="ml-2 font-normal text-slate-500">{event.actor.name || '—'}</span></p><time className="text-xs text-slate-400">{formatDateTime(event.occurred_at)}</time></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{event.progress_summary || '执行事实已更新'}</p>{event.next_step && <p className="mt-2 text-sm text-slate-600"><span className="font-medium">下一步：</span>{event.next_step}</p>}</div></li>)}</ol>}</section>
}
