import type { ExecutionPlan, KeyTaskWorkspace } from '../../api/keyTaskWorkspace'
import { formatPlanTime, statusTone } from './workspaceFormat'

export function ExecutionPlanTable({ plans, summary, onOpen }: { plans: ExecutionPlan[]; summary: KeyTaskWorkspace['plan_summary']; onOpen: (plan: ExecutionPlan) => void }) {
  return <section className="rounded-lg border border-slate-300 border-l-4 border-l-blue-700 bg-white p-5 shadow-sm" aria-label="任务计划">
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold text-slate-900">☷　任务计划</h2><p className="text-sm text-slate-600">共 {summary.total} 项　 已完成 {summary.completed}　 进行中 {summary.in_progress}　 未开始 {summary.not_started}</p></div>
    <div className="mt-4 overflow-x-auto rounded border border-slate-300">{plans.length === 0 ? <div className="grid min-h-48 place-items-center px-4 py-8 text-center text-sm text-slate-500"><div><p className="text-3xl text-slate-300">▣</p><p className="mt-3">尚未创建任务计划</p><span className="mt-4 inline-block border border-slate-300 bg-white px-3 py-1.5 text-xs text-slate-600">添加计划</span></div></div> : <table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-slate-100 text-slate-600"><tr><th className="px-4 py-3 font-medium">状态</th><th className="px-4 py-3 font-medium">计划事项</th><th className="px-4 py-3 font-medium">负责人 / 协助人</th><th className="px-4 py-3 font-medium">计划时间 / 最新进展</th></tr></thead><tbody>{plans.map((plan) => <tr key={plan.id} tabIndex={0} onClick={() => onOpen(plan)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onOpen(plan) } }} className="cursor-pointer border-t border-slate-100 text-slate-700 hover:bg-blue-50/50 focus:bg-blue-50/50 focus:outline-none"><td className="px-4 py-3"><span className={`rounded px-2 py-1 text-xs font-medium ${statusTone(plan.status)}`}>{plan.status || '未开始'}</span></td><td className="px-4 py-3 font-medium text-slate-900">{plan.title}</td><td className="px-4 py-3"><p>{plan.assignee || '未指定'}</p><p className="mt-1 text-xs text-slate-500">{plan.collaborators.length ? plan.collaborators.join('、') : '—'}</p></td><td className="px-4 py-3"><p className="whitespace-nowrap">{formatPlanTime(plan)}</p><p className="mt-1 max-w-xs truncate text-xs text-slate-500">{plan.latest_progress || plan.progress_note || '暂无正式更新'}</p></td></tr>)}</tbody></table>}</div>
  </section>
}
