import { useEffect, useMemo, useState } from 'react'
import { batchBindWecom, createAccount, fetchAccounts, fetchWecomUsers, resetAccountPassword, unbindAccountWecom, updateAccount, updateAccountStatus, type AccountItem, type WecomUserItem } from '../../api/accounts'
import { createAccountManagementPerson, deletePerson, fetchPeople, updateAccountManagementPerson } from '../../api/people'
import { SYSTEM_ROLE_NORMAL, SYSTEM_ROLE_OPTIONS, SYSTEM_ROLE_SUPER_ADMIN } from '../../domain/roles'
import type { Person } from '../../types'
import { toast } from '../../utils/toast'
import { PeopleBatchImportModal } from './PeopleBatchImportModal'
import { PersonDetailDrawer } from './PersonDetailDrawer'
import { PeopleManagementTable, type AccountStatusFilter } from './PeopleManagementTable'
import { Card, SectionTitle } from './settingsShared'
import { WecomIdentitySyncModal } from './WecomIdentitySyncModal'

export function AccountPeopleMgmtSection() {
  const [people, setPeople] = useState<Person[]>([]); const [accounts, setAccounts] = useState<AccountItem[]>([]); const [loading, setLoading] = useState(true)
  const [selectedPersonId, setSelectedPersonId] = useState<number | null>(null); const [query, setQuery] = useState(''); const [departmentFilter, setDepartmentFilter] = useState(''); const [accountStatusFilter, setAccountStatusFilter] = useState<AccountStatusFilter>('all'); const [busyAction, setBusyAction] = useState('')
  const [showNew, setShowNew] = useState(false); const [showBatchImport, setShowBatchImport] = useState(false); const [showWecomIdentitySync, setShowWecomIdentitySync] = useState(false); const [showWecomImport, setShowWecomImport] = useState(false)
  const [wecomUsers, setWecomUsers] = useState<WecomUserItem[]>([]); const [wecomSelected, setWecomSelected] = useState<Record<string, number | null>>({}); const [wecomLoading, setWecomLoading] = useState(false); const [wecomSaving, setWecomSaving] = useState(false)
  const [newName, setNewName] = useState(''); const [newRole, setNewRole] = useState(SYSTEM_ROLE_NORMAL); const [newUsername, setNewUsername] = useState(''); const [newPassword, setNewPassword] = useState(''); const [createLoginAccount, setCreateLoginAccount] = useState(true)
  async function loadAll() { setLoading(true); try { const [p, a] = await Promise.all([fetchPeople(), fetchAccounts().catch(() => [] as AccountItem[])]); setPeople(p); setAccounts(a); setSelectedPersonId((id) => id && !p.some((x) => x.id === id) ? null : id) } finally { setLoading(false) } }
  useEffect(() => { void loadAll() }, [])
  const rows = useMemo(() => people.map((person) => ({ person, account: accounts.find((account) => account.person_id === person.id) ?? null })), [people, accounts]); const selected = rows.find((row) => row.person.id === selectedPersonId) ?? null; const selectedAccount = selected?.account ?? null
  async function run(name: string, action: () => Promise<unknown>, success: string) { setBusyAction(name); try { await action(); await loadAll(); toast.success(success) } catch (e) { const m = e instanceof Error ? e.message : '操作失败'; toast.error(m); throw new Error(m) } finally { setBusyAction('') } }
  async function createPerson() { if (!newName.trim()) return; if (createLoginAccount && newPassword.length < 6) return toast.error('初始密码至少 6 位'); await run('create-person', async () => { const p = await createAccountManagementPerson({ name: newName.trim(), system_role: newRole }); if (createLoginAccount) await createAccount({ username: (newUsername || newName).trim(), password: newPassword, person_id: p.id, is_tech_admin: newRole === SYSTEM_ROLE_SUPER_ADMIN }); setShowNew(false); setNewName(''); setNewUsername(''); setNewPassword('') }, '人员已创建') }
  async function loadWecom() { setShowWecomImport(true); setWecomLoading(true); try { const users = await fetchWecomUsers(); setWecomUsers(users); setWecomSelected(Object.fromEntries(users.map((u) => [u.wecom_userid, u.preselect_account_id ?? u.bound_account_id ?? null]))) } catch (e) { toast.error(e instanceof Error ? e.message : '拉取企微通讯录失败'); setShowWecomImport(false) } finally { setWecomLoading(false) } }
  async function bindWecom() { const items = Object.entries(wecomSelected).flatMap(([wecom_userid, account_id]) => account_id ? [{ wecom_userid, account_id }] : []); if (!items.length) return toast.warning('请至少选择一个要绑定的账号'); setWecomSaving(true); try { await batchBindWecom(items); setShowWecomImport(false); await loadAll(); toast.success(`成功绑定 ${items.length} 个企业微信账号`) } finally { setWecomSaving(false) } }
  const unavailable = () => Promise.reject(new Error('该人员尚未创建登录账号'))
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><SectionTitle inline>人员与账号管理</SectionTitle><div className="flex flex-wrap gap-2"><button onClick={() => setShowBatchImport(true)} className="rounded-lg border px-3 py-1.5 text-xs">批量导入人员</button><button onClick={() => void loadWecom()} className="rounded-lg border px-3 py-1.5 text-xs text-emerald-700">拉取企微通讯录</button><button onClick={() => setShowWecomIdentitySync(true)} className="rounded-lg border px-3 py-1.5 text-xs text-cyan-700">同步部门/岗位</button><button onClick={() => setShowNew(true)} className="rounded-lg bg-sky-700 px-3 py-1.5 text-xs text-white">新建人员</button></div></div>
    {showNew && <Card><div className="flex flex-wrap gap-2"><input value={newName} onChange={(e) => setNewName(e.target.value)} placeholder="姓名（必填）" className="rounded border px-2 py-1" /><select value={newRole} onChange={(e) => setNewRole(e.target.value)}>{SYSTEM_ROLE_OPTIONS.map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</select><label className="text-xs"><input type="checkbox" checked={createLoginAccount} onChange={(e) => setCreateLoginAccount(e.target.checked)} /> 同时创建登录账号</label>{createLoginAccount && <><input value={newUsername} onChange={(e) => setNewUsername(e.target.value)} placeholder="账号名" className="rounded border px-2 py-1" /><input type="password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} placeholder="初始密码，至少 6 位" className="rounded border px-2 py-1" /></>}<button disabled={!!busyAction} onClick={() => void createPerson()} className="rounded bg-sky-700 px-3 py-1 text-white">创建</button><button onClick={() => setShowNew(false)}>取消</button></div></Card>}
    <Card>{loading ? <p className="py-8 text-center text-sm text-slate-400">加载中…</p> : <PeopleManagementTable rows={rows} query={query} department={departmentFilter} accountStatus={accountStatusFilter} onQueryChange={setQuery} onDepartmentChange={setDepartmentFilter} onAccountStatusChange={setAccountStatusFilter} onSelectPerson={setSelectedPersonId} />}</Card>
    <PersonDetailDrawer person={selected?.person ?? null} account={selectedAccount} roleOptions={SYSTEM_ROLE_OPTIONS} busyAction={busyAction} onClose={() => setSelectedPersonId(null)} onSavePerson={(p) => selected ? run('save-person', () => updateAccountManagementPerson(selected.person.id, p), '人员资料已保存') : unavailable()} onCreateAccount={(p) => selected ? run('create-account', () => createAccount({ ...p, person_id: selected.person.id, is_tech_admin: selected.person.system_role === SYSTEM_ROLE_SUPER_ADMIN }), '登录账号已创建') : unavailable()} onRenameAccount={(username) => selectedAccount ? run('rename-account', () => updateAccount(selectedAccount.id, { username }), '账号名已修改') : unavailable()} onResetPassword={(password) => selectedAccount ? run('reset-password', () => resetAccountPassword(selectedAccount.id, password), '密码已重置') : unavailable()} onToggleAccount={() => selectedAccount ? run('toggle-account', () => updateAccountStatus(selectedAccount.id, selectedAccount.status === 'active' ? 'disabled' : 'active'), '账号状态已更新') : unavailable()} onUnbindWecom={() => selectedAccount ? run('unbind-wecom', () => unbindAccountWecom(selectedAccount.id), '企业微信 ID 已解绑') : unavailable()} onDeletePerson={() => selected ? run('delete-person', () => deletePerson(selected.person.id), '人员已删除') : unavailable()} />
    {showBatchImport && <PeopleBatchImportModal onClose={() => setShowBatchImport(false)} onDone={() => { setShowBatchImport(false); void loadAll() }} />}{showWecomIdentitySync && <WecomIdentitySyncModal onClose={() => setShowWecomIdentitySync(false)} onDone={() => { setShowWecomIdentitySync(false); void loadAll() }} onProvisioned={() => void loadAll()} />}
    {showWecomImport && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30"><div className="max-h-[85vh] w-full max-w-3xl overflow-auto rounded-xl bg-white p-5"><h3 className="font-bold">企业微信通讯录</h3>{wecomLoading ? <p>加载中…</p> : <>{wecomUsers.map((u) => <div key={u.wecom_userid} className="flex gap-2 border-b py-2 text-sm"><span className="w-36">{u.wecom_name}</span><span className="w-40">{u.wecom_userid}</span><select value={wecomSelected[u.wecom_userid] ?? ''} onChange={(e) => setWecomSelected((s) => ({ ...s, [u.wecom_userid]: e.target.value ? Number(e.target.value) : null }))}><option value="">不绑定</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.username}</option>)}</select></div>)}<div className="mt-4 flex justify-end gap-2"><button onClick={() => setShowWecomImport(false)}>取消</button><button disabled={wecomSaving} onClick={() => void bindWecom()} className="rounded bg-emerald-600 px-3 py-1 text-white">确认绑定</button></div></>}</div></div>}
  </div>
}
